import { ImageResponse } from "next/og";
import { readFile } from "node:fs/promises";
import { join } from "node:path";

/**
 * The link preview card.
 *
 * Without this, scrapers (iMessage, Slack, LinkedIn) fall back to the largest
 * image they can find on the welcome page — which was a founder photo from the
 * orbiting ring. A link to a nonprofit should open with the nonprofit's mark
 * and what it does, not with somebody's face.
 *
 * Generated rather than shipped as a PNG so the copy stays editable in one
 * place and no binary has to be regenerated by hand when it changes.
 */

export const alt =
  "Axiom Pathways — connecting young talent to their passions";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

/** The line the welcome page itself leads with. */
const HEADLINE = ["Connecting young talent", "to their passions."];

export default async function OpengraphImage() {
  const [mark, inter, interSemi] = await Promise.all([
    readFile(join(process.cwd(), "public/axiom-mark.png")),
    loadInter(400),
    loadInter(600),
  ]);

  const markSrc = `data:image/png;base64,${mark.toString("base64")}`;

  const fonts = [
    inter && { name: "Inter", data: inter, weight: 400 as const, style: "normal" as const },
    interSemi && { name: "Inter", data: interSemi, weight: 600 as const, style: "normal" as const },
  ].filter(Boolean) as NonNullable<
    ConstructorParameters<typeof ImageResponse>[1]
  >["fonts"];

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          background: "#ffffff",
          padding: "60px 80px",
          fontFamily: "Inter",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 28 }}>
          {/* Rendered large on purpose: the mark is the subject of this card.
              eslint-disable-next-line @next/next/no-img-element */}
          <img src={markSrc} alt="" width={150} height={150} />
          <span
            style={{
              fontSize: 48,
              fontWeight: 600,
              letterSpacing: "-0.025em",
              color: "#15150f",
            }}
          >
            Axiom Pathways
          </span>
        </div>

        <div style={{ display: "flex", flexDirection: "column" }}>
          <span
            style={{
              fontSize: 70,
              lineHeight: 1.07,
              letterSpacing: "-0.03em",
              color: "#15150f",
            }}
          >
            {HEADLINE[0]}
          </span>
          <span
            style={{
              fontSize: 70,
              lineHeight: 1.07,
              letterSpacing: "-0.03em",
              color: "#76746a",
            }}
          >
            {HEADLINE[1]}
          </span>
        </div>

        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            borderTop: "1px solid #d7d7d6",
            paddingTop: 28,
            fontSize: 26,
            color: "#76746a",
          }}
        >
          <span>
            A nonprofit placing students into real startup work.
          </span>
          <span style={{ color: "#2f6b3d", fontWeight: 600 }}>
            axiomapply.com
          </span>
        </div>
      </div>
    ),
    { ...size, fonts },
  );
}

/**
 * Inter, for the card only.
 *
 * next/font bakes its files into the client build, not somewhere this route can
 * read, so the weights are pulled from Google's static host at generation time.
 * A failure here must not break the preview — it falls back to the renderer's
 * default face, which is worse looking but still a card without a face on it.
 */
async function loadInter(weight: 400 | 600): Promise<ArrayBuffer | null> {
  try {
    const css = await fetch(
      `https://fonts.googleapis.com/css2?family=Inter:wght@${weight}`,
      { headers: { "User-Agent": "Mozilla/5.0" } },
    ).then((response) => response.text());

    const url = css.match(/src: url\((.+?)\) format\('(opentype|truetype)'\)/)?.[1];
    if (!url) return null;

    return await fetch(url).then((response) => response.arrayBuffer());
  } catch {
    return null;
  }
}
